/**
 * The handle vocabulary, ported from voss-ask's internal/username.
 *
 * It lives beside the wire contract rather than in app code because both halves
 * need it: `app/lib/pseudonym.ts` draws handles from it, and `workers/policy.ts`
 * uses it to recognise when a message names one. A second copy of either list
 * would let the two disagree about what a handle is.
 *
 * The lists are curated lowercase ASCII and are the only thing keeping generated
 * output inside [a-z-]; there is no normalisation step on the write path. Do not
 * edit a word without checking it against that charset.
 */

export const ADJECTIVES = [
  "ancient",
  "bold",
  "brave",
  "breezy",
  "bright",
  "brisk",
  "calm",
  "cheery",
  "chill",
  "clever",
  "cosmic",
  "cosy",
  "crafty",
  "crisp",
  "curious",
  "dapper",
  "deft",
  "eager",
  "fierce",
  "fluffy",
  "fond",
  "frosty",
  "fuzzy",
  "gentle",
  "gilded",
  "glad",
  "grand",
  "happy",
  "hazy",
  "humble",
  "jazzy",
  "jolly",
  "keen",
  "kind",
  "lively",
  "lonely",
  "loyal",
  "lucky",
  "mellow",
  "merry",
  "mighty",
  "mild",
  "misty",
  "modest",
  "neat",
  "nifty",
  "noble",
  "peppy",
  "perky",
  "plucky",
  "polite",
  "proud",
  "quick",
  "quiet",
  "regal",
  "ruddy",
  "sage",
  "salty",
  "scrappy",
  "sharp",
  "silent",
  "silly",
  "sleek",
  "smart",
  "snappy",
  "snug",
  "spry",
  "steady",
  "stout",
  "sturdy",
  "sunny",
  "swift",
  "tame",
  "tidy",
  "tiny",
  "vivid",
  "wise",
  "witty",
  "zealous",
  "zesty",
] as const;

export const ANIMALS = [
  "badger",
  "beaver",
  "bison",
  "boar",
  "camel",
  "crane",
  "crow",
  "deer",
  "dove",
  "duck",
  "eagle",
  "falcon",
  "finch",
  "fox",
  "frog",
  "gecko",
  "goat",
  "goose",
  "hawk",
  "heron",
  "ibex",
  "jay",
  "koala",
  "lemur",
  "lion",
  "llama",
  "lynx",
  "magpie",
  "marmot",
  "mink",
  "mole",
  "moth",
  "mule",
  "newt",
  "okapi",
  "orca",
  "oryx",
  "ostrich",
  "otter",
  "owl",
  "panda",
  "panther",
  "parrot",
  "pony",
  "puma",
  "quail",
  "rabbit",
  "ram",
  "rat",
  "raven",
  "ray",
  "robin",
  "salmon",
  "seal",
  "shark",
  "sloth",
  "snail",
  "sparrow",
  "swan",
  "tapir",
  "tiger",
  "toad",
  "trout",
  "turtle",
  "viper",
  "walrus",
  "weasel",
  "whale",
  "wolf",
  "yak",
  "zebra",
] as const;

export const HANDLE_PATTERN = /^[a-z]+-[a-z]+(-\d{4})?$/;

export const ADJECTIVE_SET: ReadonlySet<string> = new Set(ADJECTIVES);
export const ANIMAL_SET: ReadonlySet<string> = new Set(ANIMALS);

export const WORDLIST_SIZES = {
  adjectives: ADJECTIVES.length,
  animals: ANIMALS.length,
} as const;

export function isValidHandle(value: string): boolean {
  return HANDLE_PATTERN.test(value) && value.length <= 64;
}
